import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
    <style jsx>
     {`
      h2{
        font-size: 38px;
      }
      h3{
        font-size: 28px;
      }
      `}
    </style>
      <Head>
        <title>the Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

      <main className={styles.main}>
        <h1 className={styles.title}>
        Hunting coder
        </h1>
        <div className={styles.imgWrap}>
        {/* <Image className={styles.myImg} src="/homeimg.avif" width = {237} height ={158}/></div> */}
       <img className={styles.myImg} src="/homeimg.avif" width = {237} height ={158} alt="hunting coder" /></div>
        <p className={styles.description}>
          My blog website
        </p>
      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}
